version: "3.3"
services:

  consul:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-config.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  # Define web service and envoy sidecar proxy
  web:
    build:
      context: ./consul-l7-client
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:8080
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-for-greetings-client.json
      CENTRAL_CONFIG: "/central_config/client_service_defaults.hcl;/central_config/api_service_defaults.hcl;/central_config/api_service_defaults_v1.hcl;/central_config/api_service_defaults_v2.hcl;/central_config/api_service_router.hcl"
    volumes:
      - "./consul.d:/config"
      - "./central:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "greetings-client-v1"]
    network_mode: "service:web"
  # Define api service and envoy sidecar proxy for version 1 of the service
  api_v1:
    build:
      context: ./consul-l7-api-v1
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  api_proxy_v1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-for-greetings-api-v1.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "greetings-api-v1"]
    network_mode: "service:api_v1"
  
  # Define api service and envoy sidecar proxy for version 2 of the service
  api_v2:
    build:
      context: ./consul-l7-api-v2
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  api_proxy_v2:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-for-greetings-api-v2.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "greetings-api-v2"]
    network_mode: "service:api_v2"
  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16